name: Deploy Node Application

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Create .env file
        run: echo "MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }}" >> .env
      - name: Login to docker
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build API Docker Image
        run: docker build . -t codermullins/elite-api -f backend/Dockerfile
      - name: Publish image to docker hub
        run: docker push codermullins/elite-api:latest
      # - name: Build Site Docker Image
      #   run: docker build . -t codermullins/elite-site -f frontend/Dockerfile
      # - name: Publish image to docker hub
      #   run: docker push codermullins/elite-site:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: docker pull codermullins/elite-api:latest
      - name: Delete old container
        run: docker rm -f elite-app-container
      - name: Run docker container
        run: docker run -d -p 4000:4000 --name elite-app-container codermullins/elite-api
      # - name: Pull image from docker hub
      #   run: docker pull codermullins/elite-site:latest
      # - name: Delete old container
      #   run: docker rm -f elite-app-site-container
      # - name: Run docker container
      #   run: docker run -d -p 4200:4200 --name elite-app-site-container codermullins/elite-site
